package com.nolesiak.m7_companyinfo.wsdl;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.11.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class MWLParametryWyszukiwania extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public String Krs;
    
    public String Krsy;
    
    public String Nip;
    
    public String Nipy;
    
    public String Regon;
    
    public String Regony14zn;
    
    public String Regony9zn;

    

    public void loadFromSoap(java.lang.Object paramObj,MWLExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,MWLExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Krs"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Krs = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Krs = (String)obj;
                }
                else{
                    this.Krs = "";
                }
            }
            return true;
        }
        if (info.name.equals("Krsy"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Krsy = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Krsy = (String)obj;
                }
                else{
                    this.Krsy = "";
                }
            }
            return true;
        }
        if (info.name.equals("Nip"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nip = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nip = (String)obj;
                }
                else{
                    this.Nip = "";
                }
            }
            return true;
        }
        if (info.name.equals("Nipy"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Nipy = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Nipy = (String)obj;
                }
                else{
                    this.Nipy = "";
                }
            }
            return true;
        }
        if (info.name.equals("Regon"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Regon = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Regon = (String)obj;
                }
                else{
                    this.Regon = "";
                }
            }
            return true;
        }
        if (info.name.equals("Regony14zn"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Regony14zn = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Regony14zn = (String)obj;
                }
                else{
                    this.Regony14zn = "";
                }
            }
            return true;
        }
        if (info.name.equals("Regony9zn"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Regony9zn = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Regony9zn = (String)obj;
                }
                else{
                    this.Regony9zn = "";
                }
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Krs!=null?this.Krs:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.Krsy!=null?this.Krsy:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.Nip!=null?this.Nip:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Nipy!=null?this.Nipy:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.Regon!=null?this.Regon:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.Regony14zn!=null?this.Regony14zn:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.Regony9zn!=null?this.Regony9zn:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Krs";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Krsy";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Nip";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==3)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Nipy";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==4)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Regon";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==5)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Regony14zn";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
            else if(propertyIndex==6)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Regony9zn";
                info.namespace= "http://CIS/BIR/PUBL/2014/07/DataContract";
            }
}

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
